name: Merge when ready

on:
  pull_request:
    branches: [ main ]
    types: [labeled, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    name: Auto merge if ready
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'check_suite' &&
      github.event.pull_request.base.ref == 'main' &&
      !github.event.pull_request.draft &&
      contains(github.event.pull_request.labels.*.name, 'merge')
    steps:
      - name: Merge PR (squash and delete branch) if all checks passed and approved
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO:     ${{ github.repository }}
          NUM:      ${{ github.event.pull_request.number }}
          SHA:      ${{ github.event.pull_request.head.sha }}
        run: |
          # Count approvals
          approvals=$(gh pr view "$NUM" --repo "$REPO" --json reviews \
            --jq '[.reviews[] | select(.state=="APPROVED")] | length')
          [ "$approvals" -ge 1 ] || { echo "No approvals yet"; exit 0; }

          # Ensure all required checks succeeded
          state=$(gh api repos/$REPO/commits/$SHA/status --jq .state)
          [ "$state" = "success" ] || { echo "Checks not all green"; exit 0; }

          # Merge
          gh pr merge "$NUM" --repo "$REPO" --squash --delete-branch --admin=false
