name: Enable GitHub Auto-merge on labeled PR

on:
  pull_request:
    branches: [ main ]
    types: [labeled, edited, ready_for_review, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  enable:
    if: >
      !github.event.pull_request.draft &&
      contains(github.event.pull_request.labels.*.name, 'merge') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Ensure at least 1 approval
        id: approvals
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUM:  ${{ github.event.pull_request.number }}
        run: |
          approved=$(gh api repos/$REPO/pulls/$NUM/reviews \
            --jq '[ .[] | select(.state=="APPROVED") | .user.login ] | unique | length')
          echo "count=$approved" >> $GITHUB_OUTPUT

      - name: Enable Auto-merge (squash) if approved
        if: ${{ steps.approvals.outputs.count >= 1 }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
