name: Merge when labeled and approved

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    # Only start when the merge label is applied
    if: >
      github.event.label.name == 'merge' &&
      github.event.pull_request.base.ref == 'main' &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - name: Require at least one approval
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUM:  ${{ github.event.pull_request.number }}
        run: |
          count=$(gh pr view "$NUM" --repo "$REPO" --json reviews \
            --jq '[.reviews[] | select(.state=="APPROVED") | .author.login] | unique | length')
          echo "Approvals: $count"
          if [ "$count" -lt 1 ]; then
            echo "No approvals yet. Add an approval and re-add the 'merge' label to retry."
            exit 1
          fi

      - name: Merge (branch protection enforces checks)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUM:  ${{ github.event.pull_request.number }}
        run: |
          echo "Attempting to merge PR #$NUM..."
          gh pr merge "$NUM" --repo "$REPO" --squash --delete-branch --admin=false
