name: Enable Auto-merge when ready

on:
  pull_request:
    branches: [ main ]
    types: [labeled, edited, ready_for_review, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable GitHub Auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Check merge preconditions
        id: precheck
        env:
          LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
          DRAFT:  ${{ github.event.pull_request.draft }}
          BASE:   ${{ github.event.pull_request.base.ref }}
        run: |
          echo "Labels: $LABELS"
          echo "Draft:  $DRAFT"
          echo "Base:   $BASE"
          ok=true
          if [ "$DRAFT" = "true" ]; then
            echo "PR is draft."
            ok=false
          fi
          if [ "$BASE" != "main" ]; then
            echo "PR base is not main."
            ok=false
          fi
          case ",$LABELS," in
            *,merge,*) echo "Merge label present." ;;
            *) echo "Missing 'merge' label."; ok=false ;;
          esac
          echo "ok=$ok" >> $GITHUB_OUTPUT
          if [ "$ok" != "true" ]; then
            echo "Auto-merge prerequisites not met."
            exit 1
          fi

      - name: Check approvals
        id: approvals
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUM:  ${{ github.event.pull_request.number }}
        run: |
          approved=$(gh api repos/$REPO/pulls/$NUM/reviews \
            --jq '[ .[] | select(.state=="APPROVED") | .user.login ] | unique | length')
          echo "Approvals: $approved"
          echo "count=$approved" >> $GITHUB_OUTPUT
          if [ "$approved" -lt 1 ]; then
            echo "No approvals yet."
            exit 1
          fi

      - name: Enable GitHub Auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Enabling Auto-merge on PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
