name: Auto-merge labeled PRs
on:
  pull_request:
    types: [labeled, edited, ready_for_review, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-when-approved:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'merge') && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "merge"
          MERGE_METHOD: "squash"
